<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-02-23T10:30:55-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Chicago',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
