<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-02-23T10:23:47-06:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Easter at Grace',
        ],
    ],
];
